"""add_disable_reg

Revision ID: 039bcb7dab76
Revises: 063cb4138e6d
Create Date: 2025-05-31 20:00:41.489611

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "039bcb7dab76"
down_revision = "063cb4138e6d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("runtime_server_config", sa.Column("disable_edev_registration", sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("runtime_server_config", "disable_edev_registration")
    # ### end Alembic commands ###
