"""default site control

Revision ID: 04db5645427c
Revises: 4a32b0556f8e
Create Date: 2025-05-16 13:45:03.207151

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "04db5645427c"
down_revision = "4a32b0556f8e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "archive_default_site_control",
        sa.Column("default_site_control_id", sa.INTEGER(), nullable=False),
        sa.Column("site_id", sa.INTEGER(), nullable=False),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("changed_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("import_limit_active_watts", sa.DECIMAL(precision=16, scale=2), nullable=True),
        sa.Column("export_limit_active_watts", sa.DECIMAL(precision=16, scale=2), nullable=True),
        sa.Column("generation_limit_active_watts", sa.DECIMAL(precision=16, scale=2), nullable=True),
        sa.Column("load_limit_active_watts", sa.DECIMAL(precision=16, scale=2), nullable=True),
        sa.Column("ramp_rate_percent_per_second", sa.Integer(), nullable=True),
        sa.Column("archive_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("archive_time", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("deleted_time", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("default_site_control_id", "archive_id"),
    )
    op.create_index(
        op.f("ix_archive_default_site_control_deleted_time"),
        "archive_default_site_control",
        ["deleted_time"],
        unique=False,
    )
    op.create_table(
        "default_site_control",
        sa.Column("default_site_control_id", sa.INTEGER(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("created_time", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("changed_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("import_limit_active_watts", sa.DECIMAL(precision=16, scale=2), nullable=True),
        sa.Column("export_limit_active_watts", sa.DECIMAL(precision=16, scale=2), nullable=True),
        sa.Column("generation_limit_active_watts", sa.DECIMAL(precision=16, scale=2), nullable=True),
        sa.Column("load_limit_active_watts", sa.DECIMAL(precision=16, scale=2), nullable=True),
        sa.Column("ramp_rate_percent_per_second", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["site_id"], ["site.site_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("default_site_control_id"),
    )
    op.create_index(op.f("ix_default_site_control_site_id"), "default_site_control", ["site_id"], unique=False)
    op.add_column(
        "archive_dynamic_operating_envelope",
        sa.Column("generation_limit_active_watts", sa.DECIMAL(precision=16, scale=2), nullable=True),
    )
    op.add_column(
        "archive_dynamic_operating_envelope",
        sa.Column("load_limit_active_watts", sa.DECIMAL(precision=16, scale=2), nullable=True),
    )
    op.add_column("archive_dynamic_operating_envelope", sa.Column("set_energized", sa.Boolean(), nullable=True))
    op.add_column("archive_dynamic_operating_envelope", sa.Column("set_connected", sa.Boolean(), nullable=True))
    op.add_column(
        "dynamic_operating_envelope",
        sa.Column("generation_limit_active_watts", sa.DECIMAL(precision=16, scale=2), nullable=True),
    )
    op.add_column(
        "dynamic_operating_envelope",
        sa.Column("load_limit_active_watts", sa.DECIMAL(precision=16, scale=2), nullable=True),
    )
    op.add_column("dynamic_operating_envelope", sa.Column("set_energized", sa.Boolean(), nullable=True))
    op.add_column("dynamic_operating_envelope", sa.Column("set_connected", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dynamic_operating_envelope", "set_connected")
    op.drop_column("dynamic_operating_envelope", "set_energized")
    op.drop_column("dynamic_operating_envelope", "load_limit_active_watts")
    op.drop_column("dynamic_operating_envelope", "generation_limit_active_watts")
    op.drop_column("archive_dynamic_operating_envelope", "set_connected")
    op.drop_column("archive_dynamic_operating_envelope", "set_energized")
    op.drop_column("archive_dynamic_operating_envelope", "load_limit_active_watts")
    op.drop_column("archive_dynamic_operating_envelope", "generation_limit_active_watts")
    op.drop_index(op.f("ix_default_site_control_site_id"), table_name="default_site_control")
    op.drop_table("default_site_control")
    op.drop_index(op.f("ix_archive_default_site_control_deleted_time"), table_name="archive_default_site_control")
    op.drop_table("archive_default_site_control")
    # ### end Alembic commands ###
