"""add_mup_roleflags

Revision ID: 063cb4138e6d
Revises: 1979434a3393
Create Date: 2025-05-31 19:09:35.954132

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "063cb4138e6d"
down_revision = "1979434a3393"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "archive_site_reading_type", sa.Column("role_flags", sa.INTEGER(), nullable=False, server_default="0")
    )
    op.alter_column("archive_site_reading_type", "role_flags", server_default=None)
    op.drop_index("ix_site_control_group_primacy_site_control_group_id", table_name="site_control_group")
    op.add_column("site_reading_type", sa.Column("role_flags", sa.INTEGER(), nullable=False, server_default="0"))
    op.alter_column("site_reading_type", "role_flags", server_default=None)
    op.drop_constraint("site_reading_type_all_values_uc", "site_reading_type", type_="unique")
    op.create_unique_constraint(
        "site_reading_type_all_values_uc",
        "site_reading_type",
        [
            "aggregator_id",
            "site_id",
            "uom",
            "data_qualifier",
            "flow_direction",
            "accumulation_behaviour",
            "kind",
            "phase",
            "power_of_ten_multiplier",
            "default_interval_seconds",
            "role_flags",
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("site_reading_type_all_values_uc", "site_reading_type", type_="unique")
    op.create_unique_constraint(
        "site_reading_type_all_values_uc",
        "site_reading_type",
        [
            "aggregator_id",
            "site_id",
            "uom",
            "data_qualifier",
            "flow_direction",
            "accumulation_behaviour",
            "kind",
            "phase",
            "power_of_ten_multiplier",
            "default_interval_seconds",
        ],
    )
    op.drop_column("site_reading_type", "role_flags")
    op.create_index(
        "ix_site_control_group_primacy_site_control_group_id",
        "site_control_group",
        ["primacy", "site_control_group_id"],
        unique=False,
    )
    op.drop_column("archive_site_reading_type", "role_flags")
    # ### end Alembic commands ###
