"""add_bigint_ids

Revision ID: 12e31583384d
Revises: 22491fcef4fd
Create Date: 2024-10-29 13:46:31.939346

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "12e31583384d"
down_revision = "22491fcef4fd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dynamic_operating_envelope",
        "dynamic_operating_envelope_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "site_reading",
        "site_reading_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "tariff_generated_rate",
        "tariff_generated_rate_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###

    # Ensure the ID sequences resize too
    op.execute(
        "ALTER SEQUENCE dynamic_operating_envelope_dynamic_operating_envelope_id_seq AS BIGINT MAXVALUE 9223372036854775807"
    )
    op.execute("ALTER SEQUENCE site_reading_site_reading_id_seq AS BIGINT MAXVALUE 9223372036854775807")
    op.execute(
        "ALTER SEQUENCE tariff_generated_rate_tariff_generated_rate_id_seq AS BIGINT MAXVALUE 9223372036854775807"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tariff_generated_rate",
        "tariff_generated_rate_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "site_reading",
        "site_reading_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "dynamic_operating_envelope",
        "dynamic_operating_envelope_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###

    op.execute(
        "ALTER SEQUENCE dynamic_operating_envelope_dynamic_operating_envelope_id_seq AS INTEGER MAXVALUE 2147483647"
    )
    op.execute("ALTER SEQUENCE site_reading_site_reading_id_seq AS INTEGER MAXVALUE 2147483647")
    op.execute("ALTER SEQUENCE tariff_generated_rate_tariff_generated_rate_id_seq AS INTEGER MAXVALUE 2147483647")
