"""aggregator_certificate_assignment_cascade_delete

Revision ID: 273e0c7882b3
Revises: 869e84606b0b
Create Date: 2025-07-11 13:45:28.376697

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "273e0c7882b3"
down_revision = "869e84606b0b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("aggregator_certificate_assignment_aggregator_id_fkey"),
        "aggregator_certificate_assignment",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("aggregator_certificate_assignment_certificate_id_fkey"),
        "aggregator_certificate_assignment",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("aggregator_certificate_assignment_aggregator_id_fkey"),
        "aggregator_certificate_assignment",
        "aggregator",
        ["aggregator_id"],
        ["aggregator_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("aggregator_certificate_assignment_certificate_id_fkey"),
        "aggregator_certificate_assignment",
        "certificate",
        ["certificate_id"],
        ["certificate_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("aggregator_certificate_assignment_aggregator_id_fkey"),
        "aggregator_certificate_assignment",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("aggregator_certificate_assignment_certificate_id_fkey"),
        "aggregator_certificate_assignment",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("aggregator_certificate_assignment_certificate_id_fkey"),
        "aggregator_certificate_assignment",
        "certificate",
        ["certificate_id"],
        ["certificate_id"],
    )
    op.create_foreign_key(
        op.f("aggregator_certificate_assignment_aggregator_id_fkey"),
        "aggregator_certificate_assignment",
        "aggregator",
        ["aggregator_id"],
        ["aggregator_id"],
    )
    # ### end Alembic commands ###
