"""added_groups

Revision ID: 28d4321746ee
Revises: a0b35d4fff6c
Create Date: 2024-02-23 06:22:45.780777

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "28d4321746ee"
down_revision = "a0b35d4fff6c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "site_group",
        sa.Column("site_group_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=128), nullable=False),
        sa.Column("changed_time", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("site_group_id"),
        sa.UniqueConstraint("name", name="name_uc"),
    )
    op.create_table(
        "site_group_assignment",
        sa.Column("site_group_assignment_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("changed_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("site_group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["site_group_id"], ["site_group.site_group_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["site_id"], ["site.site_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("site_group_assignment_id"),
        sa.UniqueConstraint("site_id", "site_group_id", name="site_id_site_group_id_uc"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("site_group_assignment")
    op.drop_table("site_group")
    # ### end Alembic commands ###
