"""added_defaultsitecontrol_version

Revision ID: 29a83be2701e
Revises: 8ca240a5d8f3
Create Date: 2025-12-01 15:14:36.070394

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "29a83be2701e"
down_revision = "8ca240a5d8f3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "archive_default_site_control", sa.Column("version", sa.INTEGER(), server_default="0", nullable=False)
    )
    op.alter_column("archive_default_site_control", "version", server_default=None)

    op.add_column("default_site_control", sa.Column("version", sa.INTEGER(), server_default="0", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("default_site_control", "version")
    op.drop_column("archive_default_site_control", "version")
    # ### end Alembic commands ###
