"""add_fsa_id

Revision ID: 3cf6de23d7c7
Revises: 9e3a117c1b84
Create Date: 2025-07-04 15:31:18.071781

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3cf6de23d7c7"
down_revision = "9e3a117c1b84"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("archive_site_control_group", sa.Column("fsa_id", sa.INTEGER(), nullable=False, server_default="1"))
    op.alter_column("archive_site_control_group", "fsa_id", server_default=None)
    op.add_column("archive_tariff", sa.Column("fsa_id", sa.Integer(), nullable=False, server_default="1"))
    op.alter_column("archive_tariff", "fsa_id", server_default=None)
    op.add_column("site_control_group", sa.Column("fsa_id", sa.Integer(), server_default="1", nullable=False))
    op.create_index(op.f("ix_site_control_group_fsa_id"), "site_control_group", ["fsa_id"], unique=False)
    op.add_column("tariff", sa.Column("fsa_id", sa.Integer(), server_default="1", nullable=False))
    op.create_index(op.f("ix_tariff_fsa_id"), "tariff", ["fsa_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tariff_fsa_id"), table_name="tariff")
    op.drop_column("tariff", "fsa_id")
    op.drop_index(op.f("ix_site_control_group_fsa_id"), table_name="site_control_group")
    op.drop_column("site_control_group", "fsa_id")
    op.drop_column("archive_tariff", "fsa_id")
    op.drop_column("archive_site_control_group", "fsa_id")
    # ### end Alembic commands ###
