"""added storage extension to sitecontroldefault

Revision ID: 49d00c3951b3
Revises: ed20565cc862
Create Date: 2025-12-22 15:10:42.908548

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "49d00c3951b3"
down_revision = "ed20565cc862"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "site_control_group_default",
        sa.Column("storage_target_active_watts", sa.DECIMAL(precision=16, scale=2), nullable=True),
    )
    op.add_column(
        "archive_site_control_group_default",
        sa.Column("storage_target_active_watts", sa.DECIMAL(precision=16, scale=2), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("site_control_group_default", "storage_target_active_watts")
    op.drop_column("archive_site_control_group_default", "storage_target_active_watts")
    # ### end Alembic commands ###
