"""indexes_for_site_delete

Revision ID: 4d68a22c9f62
Revises: 655e16192ee0
Create Date: 2026-07-29 18:07:22.928954

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "4d68a22c9f62"
down_revision = "655e16192ee0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_subscription_scoped_site_id"), "subscription", ["scoped_site_id"], unique=False)
    op.create_index(
        op.f("ix_subscription_condition_subscription_id"), "subscription_condition", ["subscription_id"], unique=False
    )
    op.create_index(op.f("ix_site_reading_type_site_id"), "site_reading_type", ["site_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_site_reading_type_site_id"), table_name="site_reading_type")
    op.drop_index(op.f("ix_subscription_condition_subscription_id"), table_name="subscription_condition")
    op.drop_index(op.f("ix_subscription_scoped_site_id"), table_name="subscription")
    # ### end Alembic commands ###
