"""added_registration_pin

Revision ID: 5c4cb6749db0
Revises: a69678b58de7
Create Date: 2025-02-27 17:04:49.407617

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5c4cb6749db0"
down_revision = "a69678b58de7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("archive_site", sa.Column("registration_pin", sa.INTEGER(), nullable=False, server_default="0"))
    op.alter_column("archive_site", "registration_pin", server_default=None)
    op.add_column("site", sa.Column("registration_pin", sa.INTEGER(), nullable=False, server_default="0"))
    op.alter_column("site", "registration_pin", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("site", "registration_pin")
    op.drop_column("archive_site", "registration_pin")
    # ### end Alembic commands ###
