"""updated_reading_value_size

Revision ID: 6fe657562691
Revises: 9edddd3c2d15
Create Date: 2024-04-03 15:48:25.072803

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6fe657562691"
down_revision = "9edddd3c2d15"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("site_reading", "value", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("site_reading", "value", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=False)
    # ### end Alembic commands ###
