"""doe_randomize_start

Revision ID: 7bb1448c856a
Revises: 04db5645427c
Create Date: 2025-05-16 17:08:44.570301

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7bb1448c856a"
down_revision = "04db5645427c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "archive_dynamic_operating_envelope", sa.Column("randomize_start_seconds", sa.Integer(), nullable=True)
    )
    op.add_column("dynamic_operating_envelope", sa.Column("randomize_start_seconds", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dynamic_operating_envelope", "randomize_start_seconds")
    op.drop_column("archive_dynamic_operating_envelope", "randomize_start_seconds")
    # ### end Alembic commands ###
