"""add_doe_set_point_percentage

Revision ID: 7bed3b57bae0
Revises: 54595fc3f784
Create Date: 2025-07-11 13:46:03.554205

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7bed3b57bae0"
down_revision = "54595fc3f784"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "archive_dynamic_operating_envelope",
        sa.Column("set_point_percentage", sa.DECIMAL(precision=16, scale=2), nullable=True),
    )
    op.add_column(
        "dynamic_operating_envelope",
        sa.Column("set_point_percentage", sa.DECIMAL(precision=16, scale=2), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dynamic_operating_envelope", "set_point_percentage")
    op.drop_column("archive_dynamic_operating_envelope", "set_point_percentage")
    # ### end Alembic commands ###
