"""add_ramp_time_seconds

Revision ID: 7d151bb7ddce
Revises: 273e0c7882b3
Create Date: 2025-07-23 16:17:02.038316

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7d151bb7ddce"
down_revision = "273e0c7882b3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "archive_dynamic_operating_envelope",
        sa.Column("ramp_time_seconds", sa.DECIMAL(precision=16, scale=2), nullable=True),
    )
    op.add_column(
        "dynamic_operating_envelope", sa.Column("ramp_time_seconds", sa.DECIMAL(precision=16, scale=2), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dynamic_operating_envelope", "ramp_time_seconds")
    op.drop_column("archive_dynamic_operating_envelope", "ramp_time_seconds")
    # ### end Alembic commands ###
