"""add_setpoint_cert_uniques

Revision ID: 869e84606b0b
Revises: 3cf6de23d7c7
Create Date: 2025-07-14 16:20:01.034414

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "869e84606b0b"
down_revision = "3cf6de23d7c7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_aggregator_certificate_assignment_cert_id_agg_id",
        "aggregator_certificate_assignment",
        ["certificate_id", "aggregator_id"],
    )
    op.add_column(
        "archive_dynamic_operating_envelope",
        sa.Column("set_point_percentage", sa.DECIMAL(precision=16, scale=2), nullable=True),
    )
    op.create_unique_constraint("certificate_lfdi_uc", "certificate", ["lfdi"])
    op.add_column(
        "dynamic_operating_envelope",
        sa.Column("set_point_percentage", sa.DECIMAL(precision=16, scale=2), nullable=True),
    )
    op.alter_column("certificate", "created", server_default=sa.text("now()"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dynamic_operating_envelope", "set_point_percentage")
    op.drop_constraint("certificate_lfdi_uc", "certificate", type_="unique")
    op.drop_column("archive_dynamic_operating_envelope", "set_point_percentage")
    op.drop_constraint(
        "uq_aggregator_certificate_assignment_cert_id_agg_id", "aggregator_certificate_assignment", type_="unique"
    )
    op.alter_column("certificate", "created", server_default=None)
    # ### end Alembic commands ###
