"""add_mup_identifiedobj

Revision ID: 8ca240a5d8f3
Revises: 4cc01a143a95
Create Date: 2025-09-17 13:40:48.207473

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8ca240a5d8f3"
down_revision = "4cc01a143a95"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("archive_site_reading_type", sa.Column("description", sa.VARCHAR(length=32), nullable=True))
    op.add_column("archive_site_reading_type", sa.Column("group_description", sa.VARCHAR(length=32), nullable=True))
    op.add_column("archive_site_reading_type", sa.Column("version", sa.INTEGER(), nullable=True))
    op.add_column("archive_site_reading_type", sa.Column("group_version", sa.INTEGER(), nullable=True))
    op.add_column("archive_site_reading_type", sa.Column("group_status", sa.INTEGER(), nullable=True))
    op.add_column("archive_site_reading_type", sa.Column("commodity", sa.INTEGER(), nullable=True))
    op.add_column("site_reading_type", sa.Column("description", sa.VARCHAR(length=32), nullable=True))
    op.add_column("site_reading_type", sa.Column("group_description", sa.VARCHAR(length=32), nullable=True))
    op.add_column("site_reading_type", sa.Column("version", sa.INTEGER(), nullable=True))
    op.add_column("site_reading_type", sa.Column("group_version", sa.INTEGER(), nullable=True))
    op.add_column("site_reading_type", sa.Column("group_status", sa.INTEGER(), nullable=True))
    op.add_column("site_reading_type", sa.Column("commodity", sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("site_reading_type", "commodity")
    op.drop_column("site_reading_type", "group_status")
    op.drop_column("site_reading_type", "group_version")
    op.drop_column("site_reading_type", "version")
    op.drop_column("site_reading_type", "group_description")
    op.drop_column("site_reading_type", "description")
    op.drop_column("archive_site_reading_type", "commodity")
    op.drop_column("archive_site_reading_type", "group_status")
    op.drop_column("archive_site_reading_type", "group_version")
    op.drop_column("archive_site_reading_type", "version")
    op.drop_column("archive_site_reading_type", "group_description")
    op.drop_column("archive_site_reading_type", "description")
    # ### end Alembic commands ###
