"""add_transmit_notification_log

Revision ID: 8feebfbbfe69
Revises: 5a6908457f70
Create Date: 2025-06-27 09:51:18.763889

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8feebfbbfe69"
down_revision = "5a6908457f70"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transmit_notification_log",
        sa.Column("transmit_notification_log_id", sa.Integer(), nullable=False),
        sa.Column("subscription_id_snapshot", sa.Integer(), nullable=False),
        sa.Column("transmit_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("transmit_duration_ms", sa.INTEGER(), nullable=False),
        sa.Column("notification_size_bytes", sa.INTEGER(), nullable=False),
        sa.Column("attempt", sa.INTEGER(), nullable=False),
        sa.Column("http_status_code", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("transmit_notification_log_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transmit_notification_log")
    # ### end Alembic commands ###
