"""add_site_post_rate

Revision ID: 9e3a117c1b84
Revises: 8feebfbbfe69
Create Date: 2025-07-03 14:47:56.215991

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9e3a117c1b84"
down_revision = "8feebfbbfe69"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("archive_site", sa.Column("post_rate_seconds", sa.INTEGER(), nullable=True))
    op.add_column("site", sa.Column("post_rate_seconds", sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("site", "post_rate_seconds")
    op.drop_column("archive_site", "post_rate_seconds")
    # ### end Alembic commands ###
