"""add archive_runtime_server_config

Revision ID: a1b2c3d4e5f6
Revises: 4d68a22c9f62
Create Date: 2026-08-20 00:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a1b2c3d4e5f6"
down_revision = "4d68a22c9f62"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "archive_runtime_server_config",
        sa.Column("runtime_server_config_id", sa.INTEGER(), nullable=False),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("changed_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dcap_pollrate_seconds", sa.INTEGER(), nullable=True),
        sa.Column("edevl_pollrate_seconds", sa.INTEGER(), nullable=True),
        sa.Column("fsal_pollrate_seconds", sa.INTEGER(), nullable=True),
        sa.Column("derpl_pollrate_seconds", sa.INTEGER(), nullable=True),
        sa.Column("derl_pollrate_seconds", sa.INTEGER(), nullable=True),
        sa.Column("mup_postrate_seconds", sa.INTEGER(), nullable=True),
        sa.Column("site_control_pow10_encoding", sa.INTEGER(), nullable=True),
        sa.Column("disable_edev_registration", sa.BOOLEAN(), nullable=True),
        sa.Column("archive_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("archive_time", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("deleted_time", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("archive_id"),
    )
    op.create_index(
        op.f("ix_archive_runtime_server_config_deleted_time"),
        "archive_runtime_server_config",
        ["deleted_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_archive_runtime_server_config_runtime_server_config_id"),
        "archive_runtime_server_config",
        ["runtime_server_config_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_archive_runtime_server_config_runtime_server_config_id"),
        table_name="archive_runtime_server_config",
    )
    op.drop_index(op.f("ix_archive_runtime_server_config_deleted_time"), table_name="archive_runtime_server_config")
    op.drop_table("archive_runtime_server_config")
    # ### end Alembic commands ###
