"""runtime server config

Revision ID: b56468b9b547
Revises: 7bb1448c856a
Create Date: 2025-05-18 09:05:44.994019

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b56468b9b547"
down_revision = "7bb1448c856a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "runtime_server_config",
        sa.Column("runtime_server_config_id", sa.Integer(), nullable=False),
        sa.Column("created_time", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("changed_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dcap_pollrate_seconds", sa.INTEGER(), nullable=True),
        sa.Column("edevl_pollrate_seconds", sa.INTEGER(), nullable=True),
        sa.Column("fsal_pollrate_seconds", sa.INTEGER(), nullable=True),
        sa.Column("derpl_pollrate_seconds", sa.INTEGER(), nullable=True),
        sa.Column("derl_pollrate_seconds", sa.INTEGER(), nullable=True),
        sa.Column("mup_postrate_seconds", sa.INTEGER(), nullable=True),
        sa.Column("site_control_pow10_encoding", sa.INTEGER(), nullable=True),
        sa.PrimaryKeyConstraint("runtime_server_config_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("runtime_server_config")
    # ### end Alembic commands ###
