"""site_group_archive

Revision ID: b7e50bccd7aa
Revises: 38126fedbab1
Create Date: 2026-07-29 16:49:34.195082

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b7e50bccd7aa"
down_revision = "38126fedbab1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "archive_site_group",
        sa.Column("site_group_id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=128), nullable=False),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("changed_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("default_group", sa.BOOLEAN(), nullable=False),
        sa.Column("archive_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("archive_time", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("deleted_time", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("archive_id"),
    )
    op.create_index(op.f("ix_archive_site_group_deleted_time"), "archive_site_group", ["deleted_time"], unique=False)
    op.create_index(op.f("ix_archive_site_group_site_group_id"), "archive_site_group", ["site_group_id"], unique=False)
    op.create_table(
        "archive_site_group_assignment",
        sa.Column("site_group_assignment_id", sa.INTEGER(), nullable=False),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("changed_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("site_id", sa.INTEGER(), nullable=False),
        sa.Column("site_group_id", sa.INTEGER(), nullable=False),
        sa.Column("archive_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("archive_time", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("deleted_time", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("archive_id"),
    )
    op.create_index(
        op.f("ix_archive_site_group_assignment_deleted_time"),
        "archive_site_group_assignment",
        ["deleted_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_archive_site_group_assignment_site_group_assignment_id"),
        "archive_site_group_assignment",
        ["site_group_assignment_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_archive_site_group_assignment_site_group_assignment_id"), table_name="archive_site_group_assignment"
    )
    op.drop_index(op.f("ix_archive_site_group_assignment_deleted_time"), table_name="archive_site_group_assignment")
    op.drop_table("archive_site_group_assignment")
    op.drop_index(op.f("ix_archive_site_group_site_group_id"), table_name="archive_site_group")
    op.drop_index(op.f("ix_archive_site_group_deleted_time"), table_name="archive_site_group")
    op.drop_table("archive_site_group")
    # ### end Alembic commands ###
