"""add_superseded

Revision ID: bc1ca11b5eec
Revises: 7d151bb7ddce
Create Date: 2025-07-28 16:12:57.582953

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bc1ca11b5eec"
down_revision = "7d151bb7ddce"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "archive_dynamic_operating_envelope",
        sa.Column("superseded", sa.BOOLEAN(), nullable=False, server_default="FALSE"),
    )
    op.alter_column("archive_dynamic_operating_envelope", "superseded", server_default=None)
    op.add_column(
        "dynamic_operating_envelope", sa.Column("superseded", sa.BOOLEAN(), nullable=False, server_default="FALSE")
    )
    op.alter_column("dynamic_operating_envelope", "superseded", server_default=None)
    op.drop_constraint(
        op.f("site_control_group_id_start_time_site_id_uc"), "dynamic_operating_envelope", type_="unique"
    )
    op.create_index(
        "ix_site_control_site_control_group_id_start_time_site_id",
        "dynamic_operating_envelope",
        ["site_control_group_id", "start_time", "site_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_site_control_site_control_group_id_start_time_site_id", table_name="dynamic_operating_envelope")
    op.create_unique_constraint(
        op.f("site_control_group_id_start_time_site_id_uc"),
        "dynamic_operating_envelope",
        ["site_control_group_id", "start_time", "site_id"],
    )
    op.drop_column("dynamic_operating_envelope", "superseded")
    op.drop_column("archive_dynamic_operating_envelope", "superseded")
    # ### end Alembic commands ###
