"""add mupl_pollrate_seconds

Revision ID: be0cdcf87235
Revises: f0adfeb2247d
Create Date: 2026-09-18 00:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "be0cdcf87235"
down_revision = "f0adfeb2247d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("runtime_server_config", sa.Column("mupl_pollrate_seconds", sa.INTEGER(), nullable=True))
    op.add_column("archive_runtime_server_config", sa.Column("mupl_pollrate_seconds", sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("archive_runtime_server_config", "mupl_pollrate_seconds")
    op.drop_column("runtime_server_config", "mupl_pollrate_seconds")
    # ### end Alembic commands ###
