"""add mupl_pollrate_seconds

Revision ID: beb692fa34d5
Revises: a1b2c3d4e5f6
Create Date: 2026-09-18 00:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "beb692fa34d5"
down_revision = "a1b2c3d4e5f6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("runtime_server_config", sa.Column("mupl_pollrate_seconds", sa.INTEGER(), nullable=True))
    op.add_column("archive_runtime_server_config", sa.Column("mupl_pollrate_seconds", sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("archive_runtime_server_config", "mupl_pollrate_seconds")
    op.drop_column("runtime_server_config", "mupl_pollrate_seconds")
    # ### end Alembic commands ###
