"""dercontrol_display_id

Revision ID: c230a2aa2615
Revises: ed20565cc862
Create Date: 2026-04-24 09:47:02.576306

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c230a2aa2615"
down_revision = "ed20565cc862"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("archive_dynamic_operating_envelope", sa.Column("display_id", sa.BigInteger(), nullable=True))
    op.create_index(
        "archive_doe_display_id_site_id", "archive_dynamic_operating_envelope", ["display_id", "site_id"], unique=False
    )
    op.add_column("archive_site_control_group", sa.Column("display_id", sa.Integer(), nullable=True))
    op.alter_column("archive_site_control_group", "fsa_id", existing_type=sa.INTEGER(), nullable=True)
    op.add_column("dynamic_operating_envelope", sa.Column("display_id", sa.BigInteger(), nullable=True))
    op.create_index(
        "ix_site_control_display_id_site_id", "dynamic_operating_envelope", ["display_id", "site_id"], unique=False
    )
    op.add_column("site_control_group", sa.Column("display_id", sa.Integer(), nullable=True))
    op.alter_column(
        "site_control_group", "fsa_id", existing_type=sa.INTEGER(), nullable=True, existing_server_default=None
    )
    op.create_index(op.f("ix_site_control_group_display_id"), "site_control_group", ["display_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_site_control_group_display_id"), table_name="site_control_group")
    op.alter_column(
        "site_control_group", "fsa_id", existing_type=sa.INTEGER(), nullable=False, existing_server_default=sa.text("1")
    )
    op.drop_column("site_control_group", "display_id")
    op.drop_index("ix_site_control_display_id_site_id", table_name="dynamic_operating_envelope")
    op.drop_column("dynamic_operating_envelope", "display_id")
    op.alter_column("archive_site_control_group", "fsa_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("archive_site_control_group", "display_id")
    op.drop_index("archive_doe_display_id_site_id", table_name="archive_dynamic_operating_envelope")
    op.drop_column("archive_dynamic_operating_envelope", "display_id")
    # ### end Alembic commands ###
