"""added_site_log_event

Revision ID: caa470b0f83a
Revises: 3eacce2dc06e
Create Date: 2025-03-24 16:37:22.184605

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "caa470b0f83a"
down_revision = "3eacce2dc06e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "site_log_event",
        sa.Column("site_log_event_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("created_time", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("details", sa.VARCHAR(length=32), nullable=True),
        sa.Column("extended_data", sa.INTEGER(), nullable=True),
        sa.Column("function_set", sa.SMALLINT(), nullable=False),
        sa.Column("log_event_code", sa.SMALLINT(), nullable=False),
        sa.Column("log_event_id", sa.SMALLINT(), nullable=False),
        sa.Column("log_event_pen", sa.INTEGER(), nullable=False),
        sa.Column("profile_id", sa.SMALLINT(), nullable=False),
        sa.ForeignKeyConstraint(["site_id"], ["site.site_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("site_log_event_id"),
    )
    op.create_index(
        "site_log_event_site_id_created_time_log_event_id_idx",
        "site_log_event",
        ["site_id", "created_time", "log_event_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("site_log_event_site_id_created_time_log_event_id_idx", table_name="site_log_event")
    op.drop_table("site_log_event")
    # ### end Alembic commands ###
