"""add_mup_mrid

Revision ID: d932ac3553a3
Revises: bc1ca11b5eec
Create Date: 2025-07-30 17:18:23.105460

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d932ac3553a3"
down_revision = "bc1ca11b5eec"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.schema.CreateSequence(sa.Sequence("site_reading_type_group_id_seq")))
    op.execute(
        "SELECT setval('site_reading_type_group_id_seq',  nextval('site_reading_type_site_reading_type_id_seq'));"
    )  # We will want to make sure we dont start reallocating group ids that already exist

    op.drop_constraint(op.f("site_reading_type_all_values_uc"), "site_reading_type", type_="unique")

    op.add_column("archive_site_reading_type", sa.Column("mrid", sa.VARCHAR(length=32), nullable=True))
    op.execute("UPDATE archive_site_reading_type SET mrid = cast (site_reading_type_id as varchar);")
    op.alter_column("archive_site_reading_type", "mrid", nullable=False)

    op.add_column("archive_site_reading_type", sa.Column("group_mrid", sa.VARCHAR(length=32), nullable=True))
    op.execute("UPDATE archive_site_reading_type SET group_mrid = cast (site_reading_type_id as varchar);")
    op.alter_column("archive_site_reading_type", "group_mrid", nullable=False)

    op.add_column("archive_site_reading_type", sa.Column("group_id", sa.INTEGER(), nullable=True))
    op.execute("UPDATE archive_site_reading_type SET group_id = site_reading_type_id;")
    op.alter_column("archive_site_reading_type", "group_id", nullable=False)

    op.add_column("site_reading_type", sa.Column("mrid", sa.VARCHAR(length=32), nullable=True))
    op.execute("UPDATE site_reading_type SET mrid = cast (site_reading_type_id as varchar);")
    op.alter_column("site_reading_type", "mrid", nullable=False)

    op.add_column("site_reading_type", sa.Column("group_mrid", sa.VARCHAR(length=32), nullable=True))
    op.execute("UPDATE site_reading_type SET group_mrid = cast (site_reading_type_id as varchar);")
    op.alter_column("site_reading_type", "group_mrid", nullable=False)

    op.add_column("site_reading_type", sa.Column("group_id", sa.INTEGER(), nullable=True))
    op.execute("UPDATE site_reading_type SET group_id = site_reading_type_id;")
    op.alter_column("site_reading_type", "group_id", nullable=False)

    op.create_index(
        "site_reading_type_aggregator_id_group_mrid_ix",
        "site_reading_type",
        ["aggregator_id", "group_mrid"],
        unique=False,
    )
    op.create_index(
        "site_reading_type_aggregator_id_group_id_ix", "site_reading_type", ["aggregator_id", "group_id"], unique=False
    )
    op.create_index(
        "site_reading_type_aggregator_id_site_id_group_id_ix",
        "site_reading_type",
        ["aggregator_id", "site_id", "group_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "site_reading_type_aggregator_id_site_id_mrid_uc", "site_reading_type", ["aggregator_id", "site_id", "mrid"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.schema.DropSequence(sa.Sequence("site_reading_type_group_id_seq")))
    op.drop_constraint("site_reading_type_aggregator_id_site_id_mrid_uc", "site_reading_type", type_="unique")
    op.drop_index("site_reading_type_aggregator_id_group_id_ix", table_name="site_reading_type")
    op.drop_index("site_reading_type_aggregator_id_site_id_group_id_ix", table_name="site_reading_type")
    op.drop_index("site_reading_type_aggregator_id_group_mrid_ix", table_name="site_reading_type")
    op.create_unique_constraint(
        op.f("site_reading_type_all_values_uc"),
        "site_reading_type",
        [
            "aggregator_id",
            "site_id",
            "uom",
            "data_qualifier",
            "flow_direction",
            "accumulation_behaviour",
            "kind",
            "phase",
            "power_of_ten_multiplier",
            "default_interval_seconds",
            "role_flags",
        ],
    )
    op.drop_column("site_reading_type", "group_id")
    op.drop_column("site_reading_type", "group_mrid")
    op.drop_column("site_reading_type", "mrid")
    op.drop_column("archive_site_reading_type", "group_id")
    op.drop_column("archive_site_reading_type", "group_mrid")
    op.drop_column("archive_site_reading_type", "mrid")
    # ### end Alembic commands ###
