"""add_archive_tables

Revision ID: e42aa138c308
Revises: 12e31583384d
Create Date: 2024-10-31 11:54:01.085192

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e42aa138c308"
down_revision = "12e31583384d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "archive_dynamic_operating_envelope",
        sa.Column("dynamic_operating_envelope_id", sa.BigInteger(), nullable=False),
        sa.Column("site_id", sa.INTEGER(), nullable=False),
        sa.Column("calculation_log_id", sa.INTEGER(), nullable=True),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("changed_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("import_limit_active_watts", sa.DECIMAL(precision=16, scale=2), nullable=False),
        sa.Column("export_limit_watts", sa.DECIMAL(precision=16, scale=2), nullable=False),
        sa.Column("archive_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("archive_time", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("deleted_time", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("archive_id"),
    )
    op.create_index(
        op.f("ix_archive_dynamic_operating_envelope_deleted_time"),
        "archive_dynamic_operating_envelope",
        ["deleted_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_archive_dynamic_operating_envelope_dynamic_operating_envelope_id"),
        "archive_dynamic_operating_envelope",
        ["dynamic_operating_envelope_id"],
        unique=False,
    )
    op.create_table(
        "archive_site",
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("nmi", sa.VARCHAR(length=11), nullable=True),
        sa.Column("aggregator_id", sa.INTEGER(), nullable=False),
        sa.Column("timezone_id", sa.VARCHAR(length=64), nullable=False),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("changed_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lfdi", sa.VARCHAR(length=42), nullable=False),
        sa.Column("sfdi", sa.BigInteger(), nullable=False),
        sa.Column("device_category", sa.INTEGER(), nullable=False),
        sa.Column("archive_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("archive_time", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("deleted_time", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("archive_id"),
    )
    op.create_index(op.f("ix_archive_site_deleted_time"), "archive_site", ["deleted_time"], unique=False)
    op.create_index(op.f("ix_archive_site_site_id"), "archive_site", ["site_id"], unique=False)
    op.create_table(
        "archive_site_der",
        sa.Column("site_der_id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.INTEGER(), nullable=False),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("changed_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archive_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("archive_time", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("deleted_time", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("archive_id"),
    )
    op.create_index(op.f("ix_archive_site_der_deleted_time"), "archive_site_der", ["deleted_time"], unique=False)
    op.create_index(op.f("ix_archive_site_der_site_der_id"), "archive_site_der", ["site_der_id"], unique=False)
    op.create_table(
        "archive_site_der_availability",
        sa.Column("site_der_availability_id", sa.Integer(), nullable=False),
        sa.Column("site_der_id", sa.INTEGER(), nullable=False),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("changed_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("availability_duration_sec", sa.INTEGER(), nullable=True),
        sa.Column("max_charge_duration_sec", sa.INTEGER(), nullable=True),
        sa.Column("reserved_charge_percent", sa.DECIMAL(precision=8, scale=4), nullable=True),
        sa.Column("reserved_deliver_percent", sa.DECIMAL(precision=8, scale=4), nullable=True),
        sa.Column("estimated_var_avail_value", sa.INTEGER(), nullable=True),
        sa.Column("estimated_var_avail_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("estimated_w_avail_value", sa.INTEGER(), nullable=True),
        sa.Column("estimated_w_avail_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("archive_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("archive_time", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("deleted_time", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("archive_id"),
    )
    op.create_index(
        op.f("ix_archive_site_der_availability_deleted_time"),
        "archive_site_der_availability",
        ["deleted_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_archive_site_der_availability_site_der_availability_id"),
        "archive_site_der_availability",
        ["site_der_availability_id"],
        unique=False,
    )
    op.create_table(
        "archive_site_der_rating",
        sa.Column("site_der_rating_id", sa.Integer(), nullable=False),
        sa.Column("site_der_id", sa.INTEGER(), nullable=False),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("changed_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modes_supported", sa.INTEGER(), nullable=True),
        sa.Column("abnormal_category", sa.INTEGER(), nullable=True),
        sa.Column("max_a_value", sa.INTEGER(), nullable=True),
        sa.Column("max_a_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("max_ah_value", sa.INTEGER(), nullable=True),
        sa.Column("max_ah_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("max_charge_rate_va_value", sa.INTEGER(), nullable=True),
        sa.Column("max_charge_rate_va_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("max_charge_rate_w_value", sa.INTEGER(), nullable=True),
        sa.Column("max_charge_rate_w_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("max_discharge_rate_va_value", sa.INTEGER(), nullable=True),
        sa.Column("max_discharge_rate_va_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("max_discharge_rate_w_value", sa.INTEGER(), nullable=True),
        sa.Column("max_discharge_rate_w_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("max_v_value", sa.INTEGER(), nullable=True),
        sa.Column("max_v_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("max_va_value", sa.INTEGER(), nullable=True),
        sa.Column("max_va_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("max_var_value", sa.INTEGER(), nullable=True),
        sa.Column("max_var_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("max_var_neg_value", sa.INTEGER(), nullable=True),
        sa.Column("max_var_neg_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("max_w_value", sa.INTEGER(), nullable=False),
        sa.Column("max_w_multiplier", sa.INTEGER(), nullable=False),
        sa.Column("max_wh_value", sa.INTEGER(), nullable=True),
        sa.Column("max_wh_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("min_pf_over_excited_displacement", sa.INTEGER(), nullable=True),
        sa.Column("min_pf_over_excited_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("min_pf_under_excited_displacement", sa.INTEGER(), nullable=True),
        sa.Column("min_pf_under_excited_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("min_v_value", sa.INTEGER(), nullable=True),
        sa.Column("min_v_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("normal_category", sa.INTEGER(), nullable=True),
        sa.Column("over_excited_pf_displacement", sa.INTEGER(), nullable=True),
        sa.Column("over_excited_pf_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("over_excited_w_value", sa.INTEGER(), nullable=True),
        sa.Column("over_excited_w_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("reactive_susceptance_value", sa.INTEGER(), nullable=True),
        sa.Column("reactive_susceptance_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("under_excited_pf_displacement", sa.INTEGER(), nullable=True),
        sa.Column("under_excited_pf_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("under_excited_w_value", sa.INTEGER(), nullable=True),
        sa.Column("under_excited_w_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("v_nom_value", sa.INTEGER(), nullable=True),
        sa.Column("v_nom_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("der_type", sa.INTEGER(), nullable=False),
        sa.Column("doe_modes_supported", sa.INTEGER(), nullable=True),
        sa.Column("archive_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("archive_time", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("deleted_time", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("archive_id"),
    )
    op.create_index(
        op.f("ix_archive_site_der_rating_deleted_time"), "archive_site_der_rating", ["deleted_time"], unique=False
    )
    op.create_index(
        op.f("ix_archive_site_der_rating_site_der_rating_id"),
        "archive_site_der_rating",
        ["site_der_rating_id"],
        unique=False,
    )
    op.create_table(
        "archive_site_der_setting",
        sa.Column("site_der_setting_id", sa.INTEGER(), nullable=False),
        sa.Column("site_der_id", sa.INTEGER(), nullable=False),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("changed_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modes_enabled", sa.INTEGER(), nullable=True),
        sa.Column("es_delay", sa.INTEGER(), nullable=True),
        sa.Column("es_high_freq", sa.INTEGER(), nullable=True),
        sa.Column("es_high_volt", sa.INTEGER(), nullable=True),
        sa.Column("es_low_freq", sa.INTEGER(), nullable=True),
        sa.Column("es_low_volt", sa.INTEGER(), nullable=True),
        sa.Column("es_ramp_tms", sa.INTEGER(), nullable=True),
        sa.Column("es_random_delay", sa.INTEGER(), nullable=True),
        sa.Column("grad_w", sa.INTEGER(), nullable=False),
        sa.Column("max_a_value", sa.INTEGER(), nullable=True),
        sa.Column("max_a_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("max_ah_value", sa.INTEGER(), nullable=True),
        sa.Column("max_ah_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("max_charge_rate_va_value", sa.INTEGER(), nullable=True),
        sa.Column("max_charge_rate_va_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("max_charge_rate_w_value", sa.INTEGER(), nullable=True),
        sa.Column("max_charge_rate_w_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("max_discharge_rate_va_value", sa.INTEGER(), nullable=True),
        sa.Column("max_discharge_rate_va_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("max_discharge_rate_w_value", sa.INTEGER(), nullable=True),
        sa.Column("max_discharge_rate_w_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("max_v_value", sa.INTEGER(), nullable=True),
        sa.Column("max_v_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("max_va_value", sa.INTEGER(), nullable=True),
        sa.Column("max_va_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("max_var_value", sa.INTEGER(), nullable=True),
        sa.Column("max_var_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("max_var_neg_value", sa.INTEGER(), nullable=True),
        sa.Column("max_var_neg_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("max_w_value", sa.INTEGER(), nullable=False),
        sa.Column("max_w_multiplier", sa.INTEGER(), nullable=False),
        sa.Column("max_wh_value", sa.INTEGER(), nullable=True),
        sa.Column("max_wh_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("min_pf_over_excited_displacement", sa.INTEGER(), nullable=True),
        sa.Column("min_pf_over_excited_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("min_pf_under_excited_displacement", sa.INTEGER(), nullable=True),
        sa.Column("min_pf_under_excited_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("min_v_value", sa.INTEGER(), nullable=True),
        sa.Column("min_v_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("soft_grad_w", sa.INTEGER(), nullable=True),
        sa.Column("v_nom_value", sa.INTEGER(), nullable=True),
        sa.Column("v_nom_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("v_ref_value", sa.INTEGER(), nullable=True),
        sa.Column("v_ref_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("v_ref_ofs_value", sa.INTEGER(), nullable=True),
        sa.Column("v_ref_ofs_multiplier", sa.INTEGER(), nullable=True),
        sa.Column("doe_modes_enabled", sa.INTEGER(), nullable=True),
        sa.Column("archive_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("archive_time", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("deleted_time", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("archive_id"),
    )
    op.create_index(
        op.f("ix_archive_site_der_setting_deleted_time"), "archive_site_der_setting", ["deleted_time"], unique=False
    )
    op.create_index(
        op.f("ix_archive_site_der_setting_site_der_setting_id"),
        "archive_site_der_setting",
        ["site_der_setting_id"],
        unique=False,
    )
    op.create_table(
        "archive_site_der_status",
        sa.Column("site_der_status_id", sa.Integer(), nullable=False),
        sa.Column("site_der_id", sa.INTEGER(), nullable=False),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("changed_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("alarm_status", sa.INTEGER(), nullable=True),
        sa.Column("generator_connect_status", sa.INTEGER(), nullable=True),
        sa.Column("generator_connect_status_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("inverter_status", sa.INTEGER(), nullable=True),
        sa.Column("inverter_status_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("local_control_mode_status", sa.INTEGER(), nullable=True),
        sa.Column("local_control_mode_status_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("manufacturer_status", sa.VARCHAR(length=6), nullable=True),
        sa.Column("manufacturer_status_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("operational_mode_status", sa.INTEGER(), nullable=True),
        sa.Column("operational_mode_status_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("state_of_charge_status", sa.INTEGER(), nullable=True),
        sa.Column("state_of_charge_status_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("storage_mode_status", sa.INTEGER(), nullable=True),
        sa.Column("storage_mode_status_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("storage_connect_status", sa.INTEGER(), nullable=True),
        sa.Column("storage_connect_status_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archive_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("archive_time", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("deleted_time", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("archive_id"),
    )
    op.create_index(
        op.f("ix_archive_site_der_status_deleted_time"), "archive_site_der_status", ["deleted_time"], unique=False
    )
    op.create_index(
        op.f("ix_archive_site_der_status_site_der_status_id"),
        "archive_site_der_status",
        ["site_der_status_id"],
        unique=False,
    )
    op.create_table(
        "archive_site_reading",
        sa.Column("site_reading_id", sa.BigInteger(), nullable=False),
        sa.Column("site_reading_type_id", sa.INTEGER(), nullable=False),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("changed_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("local_id", sa.INTEGER(), nullable=True),
        sa.Column("quality_flags", sa.INTEGER(), nullable=False),
        sa.Column("time_period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("time_period_seconds", sa.INTEGER(), nullable=False),
        sa.Column("value", sa.BigInteger(), nullable=False),
        sa.Column("archive_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("archive_time", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("deleted_time", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("archive_id"),
    )
    op.create_index(
        op.f("ix_archive_site_reading_deleted_time"), "archive_site_reading", ["deleted_time"], unique=False
    )
    op.create_index(
        op.f("ix_archive_site_reading_site_reading_id"), "archive_site_reading", ["site_reading_id"], unique=False
    )
    op.create_table(
        "archive_site_reading_type",
        sa.Column("site_reading_type_id", sa.INTEGER(), nullable=False),
        sa.Column("aggregator_id", sa.INTEGER(), nullable=False),
        sa.Column("site_id", sa.INTEGER(), nullable=False),
        sa.Column("uom", sa.INTEGER(), nullable=False),
        sa.Column("data_qualifier", sa.INTEGER(), nullable=False),
        sa.Column("flow_direction", sa.INTEGER(), nullable=False),
        sa.Column("accumulation_behaviour", sa.INTEGER(), nullable=False),
        sa.Column("kind", sa.INTEGER(), nullable=False),
        sa.Column("phase", sa.INTEGER(), nullable=False),
        sa.Column("power_of_ten_multiplier", sa.INTEGER(), nullable=False),
        sa.Column("default_interval_seconds", sa.INTEGER(), nullable=False),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("changed_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archive_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("archive_time", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("deleted_time", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("archive_id"),
    )
    op.create_index(
        op.f("ix_archive_site_reading_type_deleted_time"), "archive_site_reading_type", ["deleted_time"], unique=False
    )
    op.create_index(
        op.f("ix_archive_site_reading_type_site_reading_type_id"),
        "archive_site_reading_type",
        ["site_reading_type_id"],
        unique=False,
    )
    op.create_table(
        "archive_subscription",
        sa.Column("subscription_id", sa.INTEGER(), nullable=False),
        sa.Column("aggregator_id", sa.INTEGER(), nullable=False),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("changed_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resource_type", sa.INTEGER(), nullable=False),
        sa.Column("resource_id", sa.INTEGER(), nullable=True),
        sa.Column("scoped_site_id", sa.INTEGER(), nullable=True),
        sa.Column("notification_uri", sa.VARCHAR(length=2048), nullable=False),
        sa.Column("entity_limit", sa.INTEGER(), nullable=False),
        sa.Column("archive_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("archive_time", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("deleted_time", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("archive_id"),
    )
    op.create_index(
        op.f("ix_archive_subscription_deleted_time"), "archive_subscription", ["deleted_time"], unique=False
    )
    op.create_index(
        op.f("ix_archive_subscription_subscription_id"), "archive_subscription", ["subscription_id"], unique=False
    )
    op.create_table(
        "archive_subscription_condition",
        sa.Column("subscription_condition_id", sa.INTEGER(), nullable=False),
        sa.Column("subscription_id", sa.INTEGER(), nullable=False),
        sa.Column("attribute", sa.INTEGER(), nullable=False),
        sa.Column("lower_threshold", sa.INTEGER(), nullable=False),
        sa.Column("upper_threshold", sa.INTEGER(), nullable=False),
        sa.Column("archive_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("archive_time", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("deleted_time", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("archive_id"),
    )
    op.create_index(
        op.f("ix_archive_subscription_condition_deleted_time"),
        "archive_subscription_condition",
        ["deleted_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_archive_subscription_condition_subscription_condition_id"),
        "archive_subscription_condition",
        ["subscription_condition_id"],
        unique=False,
    )
    op.create_table(
        "archive_tariff",
        sa.Column("tariff_id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("dnsp_code", sa.String(length=20), nullable=False),
        sa.Column("currency_code", sa.Integer(), nullable=False),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("changed_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archive_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("archive_time", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("deleted_time", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("archive_id"),
    )
    op.create_index(op.f("ix_archive_tariff_deleted_time"), "archive_tariff", ["deleted_time"], unique=False)
    op.create_index(op.f("ix_archive_tariff_tariff_id"), "archive_tariff", ["tariff_id"], unique=False)
    op.create_table(
        "archive_tariff_generated_rate",
        sa.Column("tariff_generated_rate_id", sa.BigInteger(), nullable=False),
        sa.Column("tariff_id", sa.INTEGER(), nullable=False),
        sa.Column("site_id", sa.INTEGER(), nullable=False),
        sa.Column("calculation_log_id", sa.INTEGER(), nullable=True),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("changed_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_seconds", sa.INTEGER(), nullable=False),
        sa.Column("import_active_price", sa.DECIMAL(precision=10, scale=4), nullable=False),
        sa.Column("export_active_price", sa.DECIMAL(precision=10, scale=4), nullable=False),
        sa.Column("import_reactive_price", sa.DECIMAL(precision=10, scale=4), nullable=False),
        sa.Column("export_reactive_price", sa.DECIMAL(precision=10, scale=4), nullable=False),
        sa.Column("archive_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("archive_time", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("deleted_time", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("archive_id"),
    )
    op.create_index(
        op.f("ix_archive_tariff_generated_rate_deleted_time"),
        "archive_tariff_generated_rate",
        ["deleted_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_archive_tariff_generated_rate_tariff_generated_rate_id"),
        "archive_tariff_generated_rate",
        ["tariff_generated_rate_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_archive_tariff_generated_rate_tariff_generated_rate_id"), table_name="archive_tariff_generated_rate"
    )
    op.drop_index(op.f("ix_archive_tariff_generated_rate_deleted_time"), table_name="archive_tariff_generated_rate")
    op.drop_table("archive_tariff_generated_rate")
    op.drop_index(op.f("ix_archive_tariff_tariff_id"), table_name="archive_tariff")
    op.drop_index(op.f("ix_archive_tariff_deleted_time"), table_name="archive_tariff")
    op.drop_table("archive_tariff")
    op.drop_index(
        op.f("ix_archive_subscription_condition_subscription_condition_id"), table_name="archive_subscription_condition"
    )
    op.drop_index(op.f("ix_archive_subscription_condition_deleted_time"), table_name="archive_subscription_condition")
    op.drop_table("archive_subscription_condition")
    op.drop_index(op.f("ix_archive_subscription_subscription_id"), table_name="archive_subscription")
    op.drop_index(op.f("ix_archive_subscription_deleted_time"), table_name="archive_subscription")
    op.drop_table("archive_subscription")
    op.drop_index(op.f("ix_archive_site_reading_type_site_reading_type_id"), table_name="archive_site_reading_type")
    op.drop_index(op.f("ix_archive_site_reading_type_deleted_time"), table_name="archive_site_reading_type")
    op.drop_table("archive_site_reading_type")
    op.drop_index(op.f("ix_archive_site_reading_site_reading_id"), table_name="archive_site_reading")
    op.drop_index(op.f("ix_archive_site_reading_deleted_time"), table_name="archive_site_reading")
    op.drop_table("archive_site_reading")
    op.drop_index(op.f("ix_archive_site_der_status_site_der_status_id"), table_name="archive_site_der_status")
    op.drop_index(op.f("ix_archive_site_der_status_deleted_time"), table_name="archive_site_der_status")
    op.drop_table("archive_site_der_status")
    op.drop_index(op.f("ix_archive_site_der_setting_site_der_setting_id"), table_name="archive_site_der_setting")
    op.drop_index(op.f("ix_archive_site_der_setting_deleted_time"), table_name="archive_site_der_setting")
    op.drop_table("archive_site_der_setting")
    op.drop_index(op.f("ix_archive_site_der_rating_site_der_rating_id"), table_name="archive_site_der_rating")
    op.drop_index(op.f("ix_archive_site_der_rating_deleted_time"), table_name="archive_site_der_rating")
    op.drop_table("archive_site_der_rating")
    op.drop_index(
        op.f("ix_archive_site_der_availability_site_der_availability_id"), table_name="archive_site_der_availability"
    )
    op.drop_index(op.f("ix_archive_site_der_availability_deleted_time"), table_name="archive_site_der_availability")
    op.drop_table("archive_site_der_availability")
    op.drop_index(op.f("ix_archive_site_der_site_der_id"), table_name="archive_site_der")
    op.drop_index(op.f("ix_archive_site_der_deleted_time"), table_name="archive_site_der")
    op.drop_table("archive_site_der")
    op.drop_index(op.f("ix_archive_site_site_id"), table_name="archive_site")
    op.drop_index(op.f("ix_archive_site_deleted_time"), table_name="archive_site")
    op.drop_table("archive_site")
    op.drop_index(
        op.f("ix_archive_dynamic_operating_envelope_dynamic_operating_envelope_id"),
        table_name="archive_dynamic_operating_envelope",
    )
    op.drop_index(
        op.f("ix_archive_dynamic_operating_envelope_deleted_time"), table_name="archive_dynamic_operating_envelope"
    )
    op.drop_table("archive_dynamic_operating_envelope")
    # ### end Alembic commands ###
