"""added_sitecontroldefault

Revision ID: ed20565cc862
Revises: 29a83be2701e
Create Date: 2025-12-15 13:48:28.058413

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ed20565cc862"
down_revision = "29a83be2701e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "archive_site_control_group_default",
        sa.Column("site_control_group_default_id", sa.INTEGER(), nullable=False),
        sa.Column("site_control_group_id", sa.INTEGER(), nullable=False),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("changed_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.INTEGER(), nullable=False),
        sa.Column("import_limit_active_watts", sa.DECIMAL(precision=16, scale=2), nullable=True),
        sa.Column("export_limit_active_watts", sa.DECIMAL(precision=16, scale=2), nullable=True),
        sa.Column("generation_limit_active_watts", sa.DECIMAL(precision=16, scale=2), nullable=True),
        sa.Column("load_limit_active_watts", sa.DECIMAL(precision=16, scale=2), nullable=True),
        sa.Column("ramp_rate_percent_per_second", sa.Integer(), nullable=True),
        sa.Column("archive_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("archive_time", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("deleted_time", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("archive_id"),
    )
    op.create_index(
        op.f("ix_archive_site_control_group_default_deleted_time"),
        "archive_site_control_group_default",
        ["deleted_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_archive_site_control_group_default_site_control_group_default_id"),
        "archive_site_control_group_default",
        ["site_control_group_default_id"],
        unique=False,
    )
    op.create_table(
        "site_control_group_default",
        sa.Column("site_control_group_default_id", sa.Integer(), nullable=False),
        sa.Column("site_control_group_id", sa.Integer(), nullable=False),
        sa.Column("created_time", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("changed_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.INTEGER(), server_default="0", nullable=False),
        sa.Column("import_limit_active_watts", sa.DECIMAL(precision=16, scale=2), nullable=True),
        sa.Column("export_limit_active_watts", sa.DECIMAL(precision=16, scale=2), nullable=True),
        sa.Column("generation_limit_active_watts", sa.DECIMAL(precision=16, scale=2), nullable=True),
        sa.Column("load_limit_active_watts", sa.DECIMAL(precision=16, scale=2), nullable=True),
        sa.Column("ramp_rate_percent_per_second", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["site_control_group_id"], ["site_control_group.site_control_group_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("site_control_group_default_id"),
    )
    op.create_index(
        op.f("ix_site_control_group_default_changed_time"), "site_control_group_default", ["changed_time"], unique=False
    )
    op.create_index(
        op.f("ix_site_control_group_default_site_control_group_id"),
        "site_control_group_default",
        ["site_control_group_id"],
        unique=False,
    )
    op.drop_index("ix_archive_default_site_control_deleted_time", table_name="archive_default_site_control")
    op.drop_table("archive_default_site_control")
    op.drop_index("ix_default_site_control_changed_time", table_name="default_site_control")
    op.drop_index("ix_default_site_control_site_id", table_name="default_site_control")
    op.drop_table("default_site_control")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "default_site_control",
        sa.Column("default_site_control_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("site_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_time",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("changed_time", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("import_limit_active_watts", sa.NUMERIC(precision=16, scale=2), autoincrement=False, nullable=True),
        sa.Column("export_limit_active_watts", sa.NUMERIC(precision=16, scale=2), autoincrement=False, nullable=True),
        sa.Column(
            "generation_limit_active_watts", sa.NUMERIC(precision=16, scale=2), autoincrement=False, nullable=True
        ),
        sa.Column("load_limit_active_watts", sa.NUMERIC(precision=16, scale=2), autoincrement=False, nullable=True),
        sa.Column("ramp_rate_percent_per_second", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("version", sa.INTEGER(), server_default=sa.text("0"), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["site_id"], ["site.site_id"], name="default_site_control_site_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("default_site_control_id", name="default_site_control_pkey"),
    )
    op.create_index("ix_default_site_control_site_id", "default_site_control", ["site_id"], unique=False)
    op.create_index("ix_default_site_control_changed_time", "default_site_control", ["changed_time"], unique=False)
    op.create_table(
        "archive_default_site_control",
        sa.Column("default_site_control_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("site_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("created_time", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("changed_time", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("import_limit_active_watts", sa.NUMERIC(precision=16, scale=2), autoincrement=False, nullable=True),
        sa.Column("export_limit_active_watts", sa.NUMERIC(precision=16, scale=2), autoincrement=False, nullable=True),
        sa.Column(
            "generation_limit_active_watts", sa.NUMERIC(precision=16, scale=2), autoincrement=False, nullable=True
        ),
        sa.Column("load_limit_active_watts", sa.NUMERIC(precision=16, scale=2), autoincrement=False, nullable=True),
        sa.Column("ramp_rate_percent_per_second", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("archive_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "archive_time",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("deleted_time", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("version", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("default_site_control_id", "archive_id", name="archive_default_site_control_pkey"),
    )
    op.create_index(
        "ix_archive_default_site_control_deleted_time", "archive_default_site_control", ["deleted_time"], unique=False
    )
    op.drop_index(op.f("ix_site_control_group_default_site_control_group_id"), table_name="site_control_group_default")
    op.drop_index(op.f("ix_site_control_group_default_changed_time"), table_name="site_control_group_default")
    op.drop_table("site_control_group_default")
    op.drop_index(
        op.f("ix_archive_site_control_group_default_site_control_group_default_id"),
        table_name="archive_site_control_group_default",
    )
    op.drop_index(
        op.f("ix_archive_site_control_group_default_deleted_time"), table_name="archive_site_control_group_default"
    )
    op.drop_table("archive_site_control_group_default")
    # ### end Alembic commands ###
