"""rename dynamic_operating_envelope_id to snapshot and remove FK

Revision ID: f0f12c93d5aa
Revises: d932ac3553a3
Create Date: 2025-08-05 14:13:04.304152

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "f0f12c93d5aa"
down_revision = "d932ac3553a3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "dynamic_operating_envelope_re_dynamic_operating_envelope_i_fkey",
        "dynamic_operating_envelope_response",
        type_="foreignkey",
    )

    op.alter_column(
        table_name="dynamic_operating_envelope_response",
        column_name="dynamic_operating_envelope_id",
        new_column_name="dynamic_operating_envelope_id_snapshot",
    )

    op.drop_constraint(
        "tariff_generated_rate_response_tariff_generated_rate_id_fkey",
        "tariff_generated_rate_response",
        type_="foreignkey",
    )

    op.alter_column(
        table_name="tariff_generated_rate_response",
        column_name="tariff_generated_rate_id",
        new_column_name="tariff_generated_rate_id_snapshot",
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        table_name="tariff_generated_rate_response",
        column_name="tariff_generated_rate_id_snapshot",
        new_column_name="tariff_generated_rate_id",
    )

    op.create_foreign_key(
        "tariff_generated_rate_response_tariff_generated_rate_id_fkey",
        "tariff_generated_rate_response",
        "tariff_generated_rate",
        ["tariff_generated_rate_id"],
        ["tariff_generated_rate_id"],
        ondelete="CASCADE",
    )

    op.alter_column(
        table_name="dynamic_operating_envelope_response",
        column_name="dynamic_operating_envelope_id_snapshot",
        new_column_name="dynamic_operating_envelope_id",
    )

    op.create_foreign_key(
        "dynamic_operating_envelope_re_dynamic_operating_envelope_i_fkey",
        "dynamic_operating_envelope_response",
        "dynamic_operating_envelope",
        ["dynamic_operating_envelope_id"],
        ["dynamic_operating_envelope_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
