"""added_storage_extension

Revision ID: fe565b4c1a9e
Revises: 039bcb7dab76
Create Date: 2025-06-03 16:07:20.146546

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "fe565b4c1a9e"
down_revision = "039bcb7dab76"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "archive_default_site_control",
        sa.Column("storage_target_active_watts", sa.DECIMAL(precision=16, scale=2), nullable=True),
    )
    op.add_column(
        "archive_dynamic_operating_envelope",
        sa.Column("storage_target_active_watts", sa.DECIMAL(precision=16, scale=2), nullable=True),
    )
    op.add_column("archive_site_der_rating", sa.Column("vpp_modes_supported", sa.INTEGER(), nullable=True))
    op.add_column("archive_site_der_setting", sa.Column("min_wh_value", sa.INTEGER(), nullable=True))
    op.add_column("archive_site_der_setting", sa.Column("min_wh_multiplier", sa.INTEGER(), nullable=True))
    op.add_column("archive_site_der_setting", sa.Column("vpp_modes_enabled", sa.INTEGER(), nullable=True))
    op.add_column(
        "default_site_control",
        sa.Column("storage_target_active_watts", sa.DECIMAL(precision=16, scale=2), nullable=True),
    )
    op.add_column(
        "dynamic_operating_envelope",
        sa.Column("storage_target_active_watts", sa.DECIMAL(precision=16, scale=2), nullable=True),
    )
    op.add_column("site_der_rating", sa.Column("vpp_modes_supported", sa.INTEGER(), nullable=True))
    op.add_column("site_der_setting", sa.Column("min_wh_value", sa.INTEGER(), nullable=True))
    op.add_column("site_der_setting", sa.Column("min_wh_multiplier", sa.INTEGER(), nullable=True))
    op.add_column("site_der_setting", sa.Column("vpp_modes_enabled", sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("site_der_setting", "vpp_modes_enabled")
    op.drop_column("site_der_setting", "min_wh_multiplier")
    op.drop_column("site_der_setting", "min_wh_value")
    op.drop_column("site_der_rating", "vpp_modes_supported")
    op.drop_column("dynamic_operating_envelope", "storage_target_active_watts")
    op.drop_column("archive_site_der_setting", "vpp_modes_enabled")
    op.drop_column("archive_site_der_setting", "min_wh_multiplier")
    op.drop_column("archive_site_der_setting", "min_wh_value")
    op.drop_column("archive_site_der_rating", "vpp_modes_supported")
    op.drop_column("archive_dynamic_operating_envelope", "storage_target_active_watts")
    # ### end Alembic commands ###

    # The following were entered to deal with an upstream change that removes these tables on main branch
    op.execute(sa.text('ALTER TABLE "default_site_control" DROP COLUMN IF EXISTS "storage_target_active_watts"'))
    op.execute(
        sa.text('ALTER TABLE "archive_default_site_control" DROP COLUMN IF EXISTS "storage_target_active_watts"')
    )
